# config_example.py
# This is how you set up a config file to ensure that your private info is hidden from GitHub. My actual key is stored in a file config.py, ignored from the repository (see the .gitignore file)
# When making your config file, name it config.py 

git_token = "a bunch of random letters and numbers generated by github" 